### ISSUE TITLE
Exceptions when joining a Vanilla Server with Time & Wind CT

### ISSUE THREAD

**Issue by Qendolin** [CmdrJane/time-and-wind#10]
**Describe the bug**
When joining a vanilla server (when the screen shows 'Joining World') the game continuously throws exceptions and loading does not finish.

**To Reproduce**
1. Connect to a vanilla server
2. Wait for 'Joining World' to appear
3. Check logs since game does not crash
4. Click 'Cancel' i guess

**Information:**
 - Minecraft 1.17.1
 - Time & Wind Custom Ticker 1.0+1.17.1
 - Fabric API 0.40.1+1.17
 - [Relevant logs](https://pastebin.com/qtPcKdYA)
 - [Relevant logs](https://pastebin.com/4rCMz8Yt) (with Not Enough Crashes)

**Comment by CmdrJane** [comment]
Gonna fix that, but taw is not really intended to be a client side mod, its also required server side

**Comment by CmdrJane** [comment]
fixed in latest release on curseforge
