### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by jaquobia** [CmdrJane/time-and-wind#13]
When joining a lan-world, an Invalid Player Data error is received and the player is kicked - the day length is 192000 if that matters
no crash logs are generated
reproduced by opening a lan world with /publish 25565, and having someone join

**Comment by CmdrJane** [comment]
please specify  minecraft and mod version  you are getting crash with

**Comment by jaquobia** [comment]
1.17.1 Fabric

**Comment by jaquobia** [comment]
Sorry, I assumed at first you meant mod version as fabric/forge
ct-1.4 is the jar version

**Comment by CmdrJane** [comment]
kk will look into it once i have free time

**Comment by khiivl** [comment]
also happens on my server only on 1.4, 1.3 is fine, 1.17.1

**Comment by CmdrJane** [comment]
on dedicated server?

**Comment by CmdrJane** [comment]
possibly fixed in latest release, if not report here
