### ISSUE TITLE
Rain frequency is much higher than vanilla

### ISSUE THREAD

**Issue by purejosh** [CmdrJane/time-and-wind#18]
Hi! Loving the mod so far. I have a point of feedback though, and I'm unsure if this can be fixed, but the server that runs with this mod installed has incredibly more rain cycles than any other server I run. 

Is the slow skipping of the night causing issues with rain frequency being so high? I remember that using one person sleep mods back in 1.18 would cause way more rain cycles, and I believe this is doing the same.

**Comment by purejosh** [comment]
@CmdrJane

**Comment by CmdrJane** [comment]
try disabling slow night skip and  playing without comforts and report your findings here

**Comment by purejosh** [comment]
Well that's exactly the thing that's breaking, is the slow night skip. With slow night skip, time is effectively being fast forwarded, but if I recall correctly, the weather is reset only when you've satisfied the full sleeping condition and it skips to day. 

For example, on servers that don't use one person sleep / sleeping percentages, they have issues with rain and need to install a new plugin to help with it. That, I can strongly infer, is coming from the lack of the sleep completed event, since not all players sleep at the same time to allow skipping night. 

I can try to look into this code from Mojang, but I'm a pretty entry level developer.

**Comment by CmdrJane** [comment]
no, no need, your information is enough, thank you

**Comment by purejosh** [comment]
I very much appreciate you looking into this! 😄

**Comment by CmdrJane** [comment]
fixed in ex branch, await release soon
