### ISSUE TITLE
Rain Frequency fix in 1.18

### ISSUE THREAD

**Issue by Simplician** [CmdrJane/time-and-wind#19]
Hi; I put a pack of mods together for my family in 1.18(.2), as many mods we wanted to play have not yet been updated to 1.19. I'm really loving the longer days and sleeping mechanics in Time and Wind but I realized we were having a *lot* of rain and storms.

It appears there was another issue with the same problem and that you found a fix - and in the comments for the mod in curseforge I saw a reply that you had fixed weather cycles specifically in version 1.4.6. Sadly that does not seem to be a version available in 1.18. If it's not to much trouble, please, can I ask that you put it on the list to push that fix out to a version I can use in 1.18.2? (In the meantime it appears I will turn off night acceleration)

#18

**Comment by CmdrJane** [comment]
1.4.6 backported to 1.18.2
