### ISSUE TITLE
(Port Request) 1.19.4

### ISSUE THREAD

**Issue by Tursiops-G** [CmdrJane/time-and-wind#20]
Mod almost works as-is on 1.19.4, except for night-skip acceleration Does Not clear weather automatically when sleeping.
Work-around is to set "enableNightSkipAcceleration"to false.
Otherwise, seems to be working OK.

**Comment by CmdrJane** [comment]
fixed in latest 1.19.4 release

**Comment by Tursiops-G** [comment]
Doesn't appear to be fixed in 1.4.6
Just spent 3 days sleeping through a thunderstorm - Had to disable Night skip acceleration (again) in order to clear weather upon waking.

**Comment by CmdrJane** [comment]
i'il take a look a bit later

**Comment by CmdrJane** [comment]
fixed
