### ISSUE TITLE
Sleep does not make night over instantly

### ISSUE THREAD

**Issue by sasquott** [CmdrJane/time-and-wind#25]
setting any custom time in Overworld for day & night, or even just day, you cannot sleep to end the night (as you can in vanilla), night still goes by at the time set by default but sped up (even if not set, still speeds up but you must be in bed for the duration)

**Comment by sasquott** [comment]
so you just closed this with no response or explanation? still happening, no changelog?

**Comment by CmdrJane** [comment]
if you want help you need to provide full logs. I cant read minds and on my end it doenst happens

**Comment by CmdrJane** [comment]
also try changing enableNightSkipAcceleration to false in config

**Comment by sasquott** [comment]
apologies, but you could have said earlier. Discovered the issue was with the server, the config was still set for older version even though the mod was updated, deleting config and starting again solved it. sorry to inconvenience you

**Comment by CmdrJane** [comment]
well i kinda forgot
