### ISSUE TITLE
[Conflict] 1.3 crashes with litematica

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CmdrJane/time-and-wind#4]
Since 1.3, loading into a world (singleplayer) and waiting ~1-30 seconds results in a crash when also using [litematica](https://www.curseforge.com/minecraft/mc-mods/litematica). 

This happens even if I don't have any schematics loaded and for a newly generated world. 

crash report with only
- time-and-wind-1.3
- fabric-api-0.32.5+1.16
- litematica-fabric-1.16.4-0.0.0-dev.20210120.213004
- malilib-fabric-1.16.4-0.10.0-dev.21+arne.5

[crash-report-client.txt](https://pastebin.com/pKgD5cGQ)

crash report with all my mods, including 
- mixintrace
- blame
- notenoughcraashes

[crash-report-client.txt](https://pastebin.com/CNuSWFPv)

**Comment by CmdrJane** [comment]
Fixed in 1.3.1

**Comment by supersaiyansubtlety** [comment]
Thanks!
