### ISSUE TITLE
Not an issue, more of an accessibility suggestion

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [CmdrJane/time-and-wind#7]
Having this mod's option accessible through game rules while creating a world (or a layman's term explanation of setting it up in mod's description available through mod menu) would improve the overral experience.

I'm almost ashamed to say that me setting this bad boi up has been in vain. I failed to do it ; _ ;

upd.1 ModMenu made me so lazy I forgot that Config folder exists. feelz bad, man. feelz bad...

**Comment by CmdrJane** [comment]
Will add more proper explanation later
