### ISSUE TITLE
Technical Issue

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [CmdrJane/time-and-wind#8]
I understand this to be an Origin mod issue, but never the less creating it here, in case someone sees it and offers a sustainable solution.

Most time-based origins do not have any compitability with altered time cycles and suffer a lot because of it. That's basically all.

Issue is replicatable with any change to day-time configs of the mod itself and, most annoyingly, happen on servers as well.

Phantoms burn in the moonlight, namely.

This is created for cross-referential purpoises and my own personal ease.

**Comment by CmdrJane** [comment]
Your report is incomplete, please include your minecraft version, time and wind mod version, origins version and list of all other mods installed

**Comment by TheSunIsADeadlyLaser** [comment]
> Your report is incomplete, please include your minecraft version, time and wind mod version, origins version and list of all other mods installed

happens with nothing content-adding but origins and timewind too, but i'll fetch a modlist later as well. versions are, MC 1.17.1, Origins 1.17 1.0.3, timewind 1.4.1. Only players burn, enteties seem to be doing just fine and dandy. I don't think that it's causes by other mods, like I said, it occured on instance with nothing but client side mods.

**Comment by CmdrJane** [comment]
I've done tests and was unable to reproduce, can you reach me in discord? my discord tag is Iffy#6777

**Comment by CmdrJane** [comment]
problem still not resolved, if someone here experienced same bug please contact me

**Comment by CmdrJane** [comment]
possibly fixed in the latest version
